# Generated by Django 5.2.1 on 2025-05-21 09:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(blank=True, max_length=100)),
                ('student_id', models.CharField(blank=True, max_length=50)),
                ('g1_score', models.FloatField()),
                ('g2_score', models.FloatField()),
                ('studytime', models.IntegerField()),
                ('failures', models.IntegerField()),
                ('absences', models.IntegerField()),
                ('dalc', models.IntegerField()),
                ('walc', models.IntegerField()),
                ('health', models.IntegerField()),
                ('predicted_score', models.FloatField()),
                ('result_category', models.CharField(max_length=50)),
                ('recommendation', models.TextField()),
                ('actual_score', models.FloatField(blank=True, null=True)),
                ('prediction_diff', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
