# Generated by Django 5.2.1 on 2025-05-23 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0004_studentprediction_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprediction',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_predictions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PredictionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('student_id', models.CharField(max_length=50)),
                ('score', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('g1_score', models.FloatField()),
                ('g2_score', models.FloatField()),
                ('studytime', models.IntegerField()),
                ('failures', models.IntegerField()),
                ('absences', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prediction_histories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lịch sử dự đoán',
                'verbose_name_plural': 'Lịch sử dự đoán',
                'ordering': ['-timestamp'],
            },
        ),
    ]
