# Generated by Django 5.2.1 on 2025-05-23 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0005_alter_studentprediction_user_predictionhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predictionhistory',
            name='absences',
        ),
        migrations.RemoveField(
            model_name='predictionhistory',
            name='failures',
        ),
        migrations.RemoveField(
            model_name='predictionhistory',
            name='g1_score',
        ),
        migrations.RemoveField(
            model_name='predictionhistory',
            name='g2_score',
        ),
        migrations.RemoveField(
            model_name='predictionhistory',
            name='studytime',
        ),
        migrations.AddField(
            model_name='predictionhistory',
            name='actual_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='predictionhistory',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
