# Generated by Django 5.2.1 on 2025-05-23 11:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0006_remove_predictionhistory_absences_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionhistory',
            name='Dalc',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='predictionhistory',
            name='Fedu',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='predictionhistory',
            name='Fjob',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='predictionhistory',
            name='Medu',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='predictionhistory',
            name='Mjob',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='predictionhistory',
            name='Walc',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='predictionhistory',
            name='absences',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='predictionhistory',
            name='activities',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='predictionhistory',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='predictionhistory',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='predictionhistory',
            name='failures',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='predictionhistory',
            name='famrel',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='predictionhistory',
            name='famsize',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='predictionhistory',
            name='famsup',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='predictionhistory',
            name='freetime',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='predictionhistory',
            name='g1_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='predictionhistory',
            name='g2_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='predictionhistory',
            name='goout',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='predictionhistory',
            name='health',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='predictionhistory',
            name='higher',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='predictionhistory',
            name='internet',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='predictionhistory',
            name='nursery',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='predictionhistory',
            name='paid',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='predictionhistory',
            name='romantic',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='predictionhistory',
            name='studytime',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='predictionhistory',
            name='traveltime',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='predictionhistory',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prediction_histories', to=settings.AUTH_USER_MODEL),
        ),
    ]
